import PptxGenJS from "pptxgenjs";

type SlideSection = {
  title: string;
  bullets: string[];
};

function buildSections(content: string): SlideSection[] {
  const blocks = content
    .replace(/\r\n/g, "\n")
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean);

  return blocks.map((block, index) => {
    const lines = block
      .split("\n")
      .map((line) => line.replace(/^[-*•]\s*/, "").trim())
      .filter(Boolean);

    const [first, ...rest] = lines;

    return {
      title: first || `Section ${index + 1}`,
      bullets: rest.length > 0 ? rest : [first || ""],
    };
  });
}

export async function generatePptx(
  title: string,
  content: string,
): Promise<Buffer> {
  const pptx = new PptxGenJS();

  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "SVANS-AI";
  pptx.subject = title;
  pptx.title = title;
  pptx.company = "Vansant Platform";
  
  const titleSlide = pptx.addSlide();

  titleSlide.addText(title, {
    x: 0.8,
    y: 2.2,
    w: 11.7,
    h: 1,
    fontSize: 28,
    bold: true,
    align: "center",
    margin: 0,
  });

  titleSlide.addText("Generated by SVANS-AI", {
    x: 0.8,
    y: 3.35,
    w: 11.7,
    h: 0.5,
    fontSize: 14,
    align: "center",
    margin: 0,
  });

  const sections = buildSections(content);

  for (const section of sections.slice(0, 25)) {
    const slide = pptx.addSlide();

    slide.addText(section.title, {
      x: 0.7,
      y: 0.45,
      w: 11.9,
      h: 0.6,
      fontSize: 24,
      bold: true,
      margin: 0,
    });

    const bulletText = section.bullets
      .filter(Boolean)
      .map((bullet) => ({
        text: bullet,
        options: {
          bullet: {
            indent: 18,
          },
          breakLine: true,
        },
      }));

    if (bulletText.length > 0) {
      slide.addText(bulletText, {
        x: 0.9,
        y: 1.35,
        w: 11.2,
        h: 5.2,
        fontSize: 18,
        breakLine: false,
        valign: "top",
        margin: 0.05,
      });
    }
  }

  const output = await pptx.write({
    outputType: "nodebuffer",
  });

  return Buffer.from(output as Buffer);
}